### ISSUE TITLE
[Q] Which dependencies do I need to declare?

### ISSUE THREAD

**Issue by michelkaeser** [sorskod/webserver#1]
Which dependencies do I need to declare in my project beside your module?

If I add

```
<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.0.1</version>
    <scope>compile</scope>
</dependency>
```

the server does not start-up.

When it does start-up I get:

```
...
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;Z)Ljava/lang/String;
```

Thanks for helping me out :)

**Comment by michelkaeser** [comment]
Nevermind, the problem was that I am using Governator on top of Guice where the mode must be set to `LifecycleInjectorMode.SIMULATED_CHILD_INJECTORS` as otherwise the `BoundWebResourcesFeature` did not pick-up any resources.

So the only open question is about the `javax.ws.rs-api` API - why can it not be specified (even though it should).

Thanks

**Comment by salebab** [comment]
Jersey 2.26 depends on JAX-RS in version 2.1, so you should add:
```xml
<dependency>
  <groupId>javax.ws.rs</groupId>
  <artifactId>javax.ws.rs-api</artifactId>
  <version>2.1</version>
  <scope>compile</scope>
</dependency>
```
In your case, probably other dependency overriding transitive declaration from Jersey, so, you should declare it explicitly.

**Comment by michelkaeser** [comment]
2.1 works. Thanks!
